name: Build and Release

on:
  push:
    tags:
      - "v*"

env:
  SOLUTION_FILE_PATH: CS2External/CS2External.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

      - name: Build solution
        run: msbuild ${{ env.SOLUTION_FILE_PATH }} /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=x64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CS2External
          path: CS2External/bin/Release/CS2External.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: CS2External

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: CS2External.exe
